import bcrypt from 'bcryptjs';
import { pathToFileURL } from 'node:url';
import pool from '../lib/db.js';

const seedDefaults = String(process.env.SEED_DEFAULT_DATA || 'true').toLowerCase() !== 'false';

const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS email_settings (
    id INTEGER PRIMARY KEY,
    smtp_host TEXT,
    smtp_port INTEGER NOT NULL DEFAULT 587,
    smtp_user TEXT,
    smtp_pass TEXT,
    from_email TEXT,
    from_name TEXT NOT NULL DEFAULT 'Youth Parliament Pakistan',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS page_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_key TEXT NOT NULL UNIQUE,
    title TEXT,
    subtitle TEXT,
    content JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS slider_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL DEFAULT '',
    file_path TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS programs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    eyebrow TEXT,
    lead TEXT,
    intro_title TEXT,
    intro_text TEXT,
    hero_image TEXT,
    partner_label TEXT NOT NULL DEFAULT 'Partner',
    partner TEXT,
    donor_label TEXT NOT NULL DEFAULT 'Donor',
    donor TEXT,
    focus JSONB NOT NULL DEFAULT '[]'::jsonb,
    sort_order INTEGER NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS leadership (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    designation TEXT NOT NULL,
    photo_path TEXT,
    quote TEXT,
    bio TEXT,
    sign_text TEXT,
    wiki_url TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS core_team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    designation TEXT NOT NULL,
    photo_path TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS partners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    logo_path TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS social_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform TEXT NOT NULL UNIQUE,
    url TEXT NOT NULL DEFAULT '',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS gallery_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL DEFAULT 'image',
    title TEXT NOT NULL,
    country TEXT NOT NULL DEFAULT 'pakistan',
    file_path TEXT,
    video_url TEXT,
    video_platform TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS certificates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    file_path TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS global_engagements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    country TEXT NOT NULL DEFAULT 'general',
    file_path TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membership_id TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    father_name TEXT,
    cnic TEXT,
    province TEXT,
    city TEXT,
    country_code TEXT,
    phone TEXT,
    email TEXT,
    blood_group TEXT,
    profession TEXT,
    photo_path TEXT,
    mail_address TEXT,
    why_join TEXT,
    status TEXT NOT NULL DEFAULT 'active',
    joined_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`,
  `CREATE TABLE IF NOT EXISTS member_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    father_name TEXT,
    cnic TEXT,
    province TEXT,
    city TEXT,
    country_code TEXT NOT NULL DEFAULT '+92',
    phone TEXT,
    email TEXT NOT NULL,
    blood_group TEXT,
    profession TEXT,
    why_join TEXT,
    photo_path TEXT,
    cv_path TEXT,
    mail_address TEXT,
    status TEXT NOT NULL DEFAULT 'received',
    admin_comment TEXT NOT NULL DEFAULT '',
    membership_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  )`
];

function toUrlPath(rawPath) {
  return rawPath;
}

function valuesFrom(row, columns) {
  return columns.map((column) => row[column]);
}

async function createTables() {
  for (const statement of schemaStatements) {
    await pool.query(statement);
  }
}

async function insertIfMissing(table, conflictColumn, row) {
  const columns = Object.keys(row);
  const placeholders = columns.map((_, index) => `$${index + 1}`).join(', ');
  const values = valuesFrom(row, columns);
  await pool.query(
    `INSERT INTO ${table} (${columns.join(', ')}) VALUES (${placeholders}) ON CONFLICT (${conflictColumn}) DO NOTHING`,
    values
  );
}

async function seedPrograms() {
  const rows = [
    {
      slug: 'program-active-citizens',
      title: 'Active Citizens of Pakistan',
      eyebrow: 'Civic participation',
      lead: 'A community-focused programme for youth leadership, advocacy skills, and social responsibility.',
      hero_image: toUrlPath('reports/ACP.png'),
      donor_label: 'Donor',
      donor: 'British Council',
      partner_label: 'Partner',
      partner: '',
      sort_order: 1,
      active: true,
    },
    {
      slug: 'program-oic',
      title: 'Organisation of Islamic Conferences',
      eyebrow: 'Humanitarian response',
      lead: 'A disaster recovery programme for rehabilitation, housing, and community dignity in flood-affected areas.',
      hero_image: toUrlPath('reports/oic_modern_village_rehabilitation.png'),
      partner_label: 'Partner',
      partner: 'Organization of Islamic Cooperation (OIC)',
      donor_label: 'Donor',
      donor: '',
      sort_order: 2,
      active: true,
    },
    {
      slug: 'program-human-rights-education',
      title: 'Human Rights Education',
      eyebrow: 'Rights and inclusion',
      lead: 'A practical program for awareness, dignity, inclusion, and social justice.',
      hero_image: toUrlPath('reports/12A9A47E-78F1-40F4-AF0A-82B92F1F858F.png'),
      partner_label: 'Partner',
      partner: 'SIDA',
      donor_label: 'Donor',
      donor: '',
      sort_order: 3,
      active: true,
    },
    {
      slug: 'program-youth-action-for-democracy',
      title: 'Youth Action for Democracy',
      eyebrow: 'Democratic governance',
      lead: 'A nationwide initiative for democratic participation and electoral awareness among young people.',
      hero_image: toUrlPath('reports/Strengthening democratic participation and informed electoral engagement..png'),
      partner_label: 'Partner',
      partner: 'Election Commission of Pakistan',
      donor_label: 'Donor',
      donor: 'United Nations Democracy Fund (UNDEF)',
      sort_order: 4,
      active: true,
    },
    {
      slug: 'program-umeed-e-jawan',
      title: 'Umeed-e-Jawan',
      eyebrow: 'Skills and livelihoods',
      lead: 'A youth empowerment and vocational skills development initiative implemented in Southern Punjab.',
      hero_image: toUrlPath('reports/umeed_e_jawan_usaid_funded.png'),
      partner_label: 'Partner',
      partner: '',
      donor_label: 'Donor',
      donor: 'USAID',
      sort_order: 5,
      active: true,
    },
    {
      slug: 'program-nojawano-ka-wazir-e-azam',
      title: 'Kon Hoga Nojawano Ka Wazir-e-Azam',
      eyebrow: 'Broadcast partner: ATV (Pakistan)',
      lead: 'A flagship youth leadership and political awareness programme aired on ATV.',
      hero_image: toUrlPath('reports/wazerazam.png'),
      partner_label: 'Broadcast Partner',
      partner: 'ATV (Pakistan)',
      donor_label: 'Donor',
      donor: '',
      sort_order: 6,
      active: true,
    },
  ];

  for (const row of rows) {
    await insertIfMissing('programs', 'slug', {
      slug: row.slug,
      title: row.title,
      eyebrow: row.eyebrow,
      lead: row.lead,
      intro_title: null,
      intro_text: null,
      hero_image: row.hero_image,
      partner_label: row.partner_label,
      partner: row.partner || null,
      donor_label: row.donor_label,
      donor: row.donor || null,
      focus: JSON.stringify([]),
      sort_order: row.sort_order,
      active: row.active,
    });
  }
}

async function seedPages() {
  const pages = [
    {
      page_key: 'about',
      title: 'Our History',
      subtitle: 'Youth Parliament Pakistan is built around leadership, service, and youth empowerment.',
      content: {
        eyebrow: 'History of YPP',
        heroImage: 'assets/about-us-image.jpg',
        sectionEyebrow: 'Founding vision',
        sectionTitle: 'Creating a platform for youth-led change',
        paragraphs: [
          'Youth Parliament Pakistan was conceived, conceptualized, and planned to empower the youth of Pakistan with the ability to understand the importance of their role in community service and to nurture their leadership qualities.',
          'The organization works through civic education, policy dialogue, human rights awareness, and community-focused youth engagement across Pakistan.'
        ],
        thematicTitle: 'What We Aim to Achieve',
        thematicAreas: [
          {
            title: 'Democratic Governance & Civic Participation',
            text: 'Promoting democratic values, constitutional awareness, civic engagement, and active citizenship among young people through parliamentary simulations, policy dialogue, and institutional learning.'
          },
          {
            title: 'Human Rights, Social Justice & Inclusion',
            text: 'Advancing awareness and protection of human rights with a focus on gender equality, minority rights, child protection, and social inclusion of marginalized communities.'
          },
          {
            title: 'Youth Leadership Development & Capacity Building',
            text: 'Strengthening leadership competencies, critical thinking, communication skills, ethical leadership, and civic responsibility among youth through structured training and mentorship programs.'
          },
          {
            title: 'Policy Research, Dialogue & Advocacy',
            text: 'Facilitating evidence-based policy discussions, youth-led research, and dialogue platforms that enable young people to contribute to national policy development and reform processes.'
          },
          {
            title: 'Electoral Awareness & Civic Education',
            text: 'Promoting voter education, electoral awareness, democratic participation, and informed citizenship to strengthen participatory democracy in Pakistan.'
          },
          {
            title: 'Youth-Led Development & Community Empowerment',
            text: 'Supporting youth-driven initiatives that address local development challenges in education, health, poverty alleviation, and social welfare through community-based action.'
          }
        ]
      }
    },
    {
      page_key: 'home_impact',
      title: 'Our Impact',
      subtitle: 'Measured through action, reach, and sustained youth engagement.',
      content: {
        eyebrow: 'Impact at a glance',
        description: 'From civic education and leadership development to humanitarian response and youth livelihood initiatives, YPP works across Pakistan with young people, institutions, and communities.',
        image1: 'assets/pakistan-youth-group.png',
        image2: 'assets/about-us-image.jpg',
        counters: [
          { value: 6, label: 'Program tracks', suffix: '' },
          { value: 4, label: 'Leadership profiles', suffix: '' },
          { value: 6, label: 'Global engagements', suffix: '' },
          { value: 5, label: 'Official documents', suffix: '' }
        ]
      }
    }
  ];

  for (const page of pages) {
    await insertIfMissing('page_content', 'page_key', {
      page_key: page.page_key,
      title: page.title,
      subtitle: page.subtitle,
      content: JSON.stringify(page.content),
    });
  }
}

async function seedSocialLinks() {
  const rows = [
    { platform: 'facebook', url: 'https://www.facebook.com/YouthPPk' },
    { platform: 'instagram', url: 'https://www.instagram.com/youth_ppk/' },
    { platform: 'x', url: 'https://x.com/youth_ppk' },
    { platform: 'linkedin', url: 'https://www.linkedin.com/company/youth_ppk/' },
  ];

  for (const row of rows) {
    await insertIfMissing('social_links', 'platform', row);
  }
}

async function seedEmailSettings() {
  await insertIfMissing('email_settings', 'id', {
    id: 1,
    smtp_host: '',
    smtp_port: 587,
    smtp_user: '',
    smtp_pass: '',
    from_email: 'info@ypp.org.pk',
    from_name: 'Youth Parliament Pakistan',
  });
}

async function seedAdminUser() {
  const { rows: countRows } = await pool.query('SELECT COUNT(*)::int AS count FROM admin_users');
  if (countRows[0].count > 0) return;

  const email = process.env.ADMIN_BOOTSTRAP_EMAIL?.trim();
  const password = process.env.ADMIN_BOOTSTRAP_PASSWORD;

  if (!email || !password) {
    console.warn('No admin user exists yet. Set ADMIN_BOOTSTRAP_EMAIL and ADMIN_BOOTSTRAP_PASSWORD before first deploy, or create an admin user manually.');
    return;
  }

  const passwordHash = await bcrypt.hash(password, 12);
  await insertIfMissing('admin_users', 'email', {
    name: process.env.ADMIN_BOOTSTRAP_NAME || 'YPP Admin',
    email,
    password_hash: passwordHash,
  });
}

async function seedIfEmpty(table, rows) {
  if (!seedDefaults) return;
  const { rows: countRows } = await pool.query(`SELECT COUNT(*)::int AS count FROM ${table}`);
  if (countRows[0].count > 0) return;

  for (const row of rows) {
    const columns = Object.keys(row);
    const placeholders = columns.map((_, index) => `$${index + 1}`).join(', ');
    const values = valuesFrom(row, columns);
    await pool.query(`INSERT INTO ${table} (${columns.join(', ')}) VALUES (${placeholders})`, values);
  }
}

async function seedCollections() {
  await seedIfEmpty('slider_items', [
    { title: 'Youth Parliament Pakistan', file_path: 'reports/slider/Slider Home/0.jpg', sort_order: 1 },
    { title: 'Leadership and service', file_path: 'reports/slider/Slider Home/1.jpg', sort_order: 2 },
    { title: 'Youth engagement', file_path: 'reports/slider/Slider Home/2.jpg', sort_order: 3 },
    { title: 'Community impact', file_path: 'reports/slider/Slider Home/4.jpg', sort_order: 4 },
  ]);

  await seedIfEmpty('leadership', [
    {
      full_name: 'Abrar Ul Haq',
      designation: 'Founder & Chairman',
      photo_path: 'reports/WhatsApp Image 2026-06-19 at 20.45.24.jpeg',
      quote: '',
      bio: 'Founder and Chairman of Youth Parliament Pakistan. He established the organization to support youth leadership, civic participation, and community service across Pakistan.',
      sign_text: '',
      wiki_url: '',
      sort_order: 1,
    },
    {
      full_name: 'Dr. Abdul Rahim Babar Dogar',
      designation: 'Vice Chairman',
      photo_path: 'reports/c0943570-5aba-46a0-b9b3-57e7a5186ec9.jpg',
      quote: '',
      bio: 'Vice Chairman supporting organizational strategy, partnerships, and institutional engagement.',
      sign_text: '',
      wiki_url: '',
      sort_order: 2,
    },
    {
      full_name: 'Ubaid-Ur-Rehman Qureshi',
      designation: 'President',
      photo_path: 'reports/WhatsApp Image 2026-06-19 at 19.55.41.jpeg',
      quote: '',
      bio: 'President leading programme delivery, youth mobilisation, and national coordination.',
      sign_text: '',
      wiki_url: '',
      sort_order: 3,
    },
    {
      full_name: 'Hammad Malik',
      designation: 'General Secretary',
      photo_path: 'reports/694904d1-23bd-47b3-b7d7-e228d5d30c51.jpg',
      quote: '',
      bio: 'General Secretary overseeing coordination, communications, and day-to-day organisational operations.',
      sign_text: '',
      wiki_url: '',
      sort_order: 4,
    },
  ]);

  await seedIfEmpty('core_team', [
    { full_name: 'Qaiser Jamil', designation: 'Coordinator AJK', photo_path: 'reports/Qaiser Jamil - Coordinator AJK.jpeg', sort_order: 1 },
    { full_name: 'Fasil Jamshed', designation: 'Coordinator KPK', photo_path: 'reports/Fasil Jamshed - Coordinator KPK.jpeg', sort_order: 2 },
    { full_name: 'Hira Bilal', designation: 'Executive Member', photo_path: 'reports/Hira Bilal - Executive Member.jpeg', sort_order: 3 },
    { full_name: 'Sidra Akhtar', designation: 'Executive Member', photo_path: 'reports/Sidra Akhtar - Exective Member.jpeg', sort_order: 4 },
    { full_name: 'Zobia Khurshid', designation: 'Executive Member', photo_path: 'reports/Zobia Khurshid - Executive Member.jpeg', sort_order: 5 },
    { full_name: 'Bakhtwar Mahmood', designation: 'Executive Member', photo_path: 'reports/Bakhtwar Mahmood - Executive Member.jpeg', sort_order: 6 },
  ]);

  await seedIfEmpty('partners', [
    { name: 'Partner Logo 1', logo_path: 'assets/partnerlogos/1.png', sort_order: 1 },
    { name: 'Partner Logo 2', logo_path: 'assets/partnerlogos/2.png', sort_order: 2 },
    { name: 'Partner Logo 3', logo_path: 'assets/partnerlogos/3.png', sort_order: 3 },
    { name: 'Partner Logo 4', logo_path: 'assets/partnerlogos/4.png', sort_order: 4 },
    { name: 'Partner Logo 5', logo_path: 'assets/partnerlogos/5.png', sort_order: 5 },
    { name: 'Partner Logo 6', logo_path: 'assets/partnerlogos/6.png', sort_order: 6 },
    { name: 'Partner Logo 7', logo_path: 'assets/partnerlogos/7.png', sort_order: 7 },
    { name: 'Partner Logo 8', logo_path: 'assets/partnerlogos/8.png', sort_order: 8 },
    { name: 'Partner Logo 9', logo_path: 'assets/partnerlogos/9.png', sort_order: 9 },
    { name: 'Partner Logo 10', logo_path: 'assets/partnerlogos/10.png', sort_order: 10 },
  ]);

  await seedIfEmpty('gallery_items', [
    { type: 'image', title: 'Youth delegation', country: 'pakistan', file_path: 'reports/slider/gallery/3.jpg' },
    { type: 'image', title: 'International engagement', country: 'uk', file_path: 'reports/slider/gallery/6.jpg' },
    { type: 'image', title: 'Programme showcase', country: 'usa', file_path: 'reports/slider/gallery/cb1c2d84-701a-40d5-8b24-bac160593e5b.JPG' },
    { type: 'image', title: 'Youth forum', country: 'general', file_path: 'reports/slider/gallery/S2.png' },
    { type: 'image', title: 'Community gathering', country: 'pakistan', file_path: 'reports/slider/gallery/2c3388c9-8961-49b5-a914-4c4729947ab6.JPG' },
  ]);

  await seedIfEmpty('certificates', [
    { title: 'Certificate of Registration', description: 'Registered under the Societies Registration Act, XXI of 1860. Issued by City District Government, Lahore - March 2008.', file_path: 'reports/Pakistan_YPP_Certificate-of-Registration.jpg' },
    { title: 'CEC Notification - Page 1', description: 'Central Executive Council (CEC) of Youth Parliament Pakistan - Interim Setup notification.', file_path: 'reports/C1.jpeg' },
    { title: 'Cabinet Notification - Page 2', description: 'Cabinet members and designations. Dated 13th September, 2019. Signed by Chairman Abrar-Ul-Haq.', file_path: 'reports/C2.jpeg' },
    { title: 'YPP Official Document', description: 'Organizational overview, mission statement, thematic areas, and international partnerships of Youth Parliament Pakistan.', file_path: 'reports/YPP-Document.jpg' },
    { title: 'Board of Directors', description: 'Official memorandum of society formation with founding board members, signed and registered at Lahore.', file_path: 'reports/BODs-YPP.jpg' },
  ]);

  await seedIfEmpty('global_engagements', [
    { title: 'UK Report 2025', description: 'Latest United Kingdom delegation and engagement report.', country: 'uk', file_path: 'reports/UK Report 2025.pdf', sort_order: 1 },
    { title: 'UK Visit Report 2024', description: 'Official delegation report from the 2024 United Kingdom visit.', country: 'uk', file_path: 'reports/2024 UK visit Report.pdf', sort_order: 2 },
    { title: 'UK Report 2023', description: 'Annual UK visit and partnership engagement documentation.', country: 'uk', file_path: 'reports/UK Report 2023.pdf', sort_order: 3 },
    { title: 'UK Report 2022', description: 'YPP delegation report from the 2022 United Kingdom visit.', country: 'uk', file_path: 'reports/UK Report 2022.pdf', sort_order: 4 },
    { title: 'USA UN Visit Report', description: 'Official report from the YPP delegation visit to the United Nations, USA.', country: 'usa', file_path: 'reports/USA UN Visit Report.pdf', sort_order: 5 },
    { title: 'Next Generation Report', description: 'Youth Parliament Pakistan next generation leadership and vision report.', country: 'general', file_path: 'reports/next-generation-report.pdf', sort_order: 6 },
  ]);
}

export async function ensureDatabase() {
  await createTables();

  if (seedDefaults) {
    await seedPrograms();
    await seedPages();
    await seedSocialLinks();
    await seedEmailSettings();
    await seedCollections();
  }

  await seedAdminUser();
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;

if (isMain) {
  ensureDatabase()
    .then(async () => {
      await pool.end();
      console.log('Database is ready.');
    })
    .catch(async (error) => {
      console.error(error);
      await pool.end().catch(() => {});
      process.exit(1);
    });
}
